site_name: Mitschriften
# site_description: Project documentation with Markdown.
nav:
  - Home: index.md
  - Datentechnik:
    - IP-Adresse: Datentechnik/IP-Adresse.md
    - Netzwerkadresse: Datentechnik/Netzwerkadresse.md
    - Broadcastadresse: Datentechnik/Broadcastadresse.md
    - Datentechnik: Datentechnik/Datentechnik.md
    - Zahlensysteme: Datentechnik/Zahlensysteme/Zahlensysteme.md
  - Webdevelopment:
    - HTML:
      - HTML Basics: Webdevelopment/HTML/HTML_Basics.md
      - Kontaktformular: Webdevelopment/HTML/Kontaktforumlar.md
      - Responsive Design: Webdevelopment/HTML/Responsive_Design.md
    - CSS:
      - CSS Basics: Webdevelopment/CSS/CSS_Basics.md
      - Box-Model: Webdevelopment/CSS/Box Model-Flexbox-Grid.md
  - IT-Recht:
    - Arbeitsrecht: IT-Recht/Arbeitsrecht.md
    - Datenschutz-Prüfungsfragen_aus_den_FIA-Unterlagen_Teil1: IT-Recht/Datenschutz-Prüfungsfragen_aus_den_FIA-Unterlagen_Teil1.md
    - Datenschutz-Prüfungsfragen_aus_den_FIA-Unterlagen_Teil2: IT-Recht/Datenschutz-Prüfungsfragen_aus_den_FIA-Unterlagen_Teil2.md
    - Garantie-und_Gewährleistung: IT-Recht/Garantie-und_Gewährleistung.md
    - Impressum und Offenlegung: IT-Recht/Impressum-und-Offenlegung.md
    - IT Securitiy Data Breach: IT-Recht/IT-Security-Data-Breach.md
    - Telekommunikationsgesetz (TKG) 2021: IT-Recht/Telekommunikationsgesetz-(TKG)-2021.md

    
theme: 
  name: material
# theme: readthedocs
  primary: indigo
  accent: indigo
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Hinotori91
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/Hinotori91
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/petra-camondo-5836bb109/

# copyright: Copyright &copy; Petra Camondo


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - ./css/style.css
